export const SITE_CONSTANTS = {
  ABOUT_ME_TITLE: "about me",
  ABOUT_MY_CAT_TITLE: "about my cat",
  ANIMATION_PLAY_STATE_PAUSED: "paused",
  ANIMATION_PLAY_STATE_RUNNING: "running",
  BLUESKY_TITLE: "Bluesky",
  BLUESKY_URL: "https://bsky.app/profile/sarahjacques.bsky.social",
  CONTACT_TITLE: "contact me",
  DEFAULT_SITE_THEME: "ube",
  DEFAULT_ANIMATION_PLAY_STATE: "running",
  GITHUB_TITLE: "GitHub",
  GITHUB_URL: "https://github.com/crystal-hearts/sj-personal-homepage",
  HOME_TITLE: "home",
  LINKEDIN_TITLE: "LinkedIn",
  LINKEDIN_URL: "https://www.linkedin.com/in/sarah-c-jacques",
  PAGE_ID: "page",
  PAUSE_BUTTON_ID: "pause-button",
  PAUSE_BUTTON_TITLE: "Play animations",
  PLAY_BUTTON_ID: "play-button",
  PLAY_BUTTON_TITLE: "Pause animations",
  SETTINGS_BUTTON_ID: "settings-button",
  SETTINGS_BUTTON_TITLE: "Settings",
  SETTINGS_MODAL_ID: "settings-modal",
  SETTINGS_MODAL_TITLE: "site flavor",
  ABOUT_SITE_TITLE: "about this site",
};
